name: 'Bamboo HR API Driven Provisioning Entra ID'
description: 'Provisioning Entra ID from Bamboo HR'
author: 'Suryendu Bhattacharyya'
inputs:
  bamboo_api_key:
    description: 'Bamboo API Key'
    required: true
  bamboo_subdomain:
    description: 'Bamboo Subdomain'
    required: true
  client_id:
    description: 'Entra ID Client ID'
    required: true
  client_secret:
    description: 'Entra ID Client Secret'
    required: true
  serviceprincipalid:
    description: 'Entra ID Service Principal ID'
    required: true
  tenantid:
    description: 'Entra ID Tenant ID'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Provisioning Entra ID'
      id: 'provisioning-entra-id'
      run: |
        Set-Location -Path ${{ github.action_path }}
        $parameters = @{
           APIKey = "${{ inputs.bamboo_api_key }}"
           Subdomain = "${{ inputs.bamboo_subdomain }}"
           ClientID = "${{ inputs.client_id }}"
           ClientSecret = "${{ inputs.client_secret }}"
           ServicePrincipalID = "${{ inputs.serviceprincipalid }}"
           TenantId = "${{ inputs.tenantid }}"
          }
          .\APIDrivenProvisioningPowershell.ps1 @parameters 
      shell: pwsh
branding:
  color: 'blue'
  icon: 'user-plus'
  