name: 'Bamboo HR API Driven Provisioning Entra ID'
description: 'Provisioning Entra ID from Bamboo HR'
inputs:
  bamboo_api_key:
    description: 'Bamboo API Key'
    required: true
  bamboo_subdomain:
    description: 'Bamboo Subdomain'
    required: true
  client_id:
    description: 'Entra ID Client ID'
    required: true
  client_secret:
    description: 'Entra ID Client Secret'
    required: true
  serviceprincipalid:
    description: 'Entra ID Service Principal ID'
    required: true
  tenantid:
    description: 'Entra ID Tenant ID'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Provisioning Entra ID'
      id: 'provisioning-entra-id'
      run: |
        echo "Bamboo API Key: ${{ inputs.bamboo_api_key }}"
        echo "Bamboo Subdomain: ${{ inputs.bamboo_subdomain }}"
        echo "Entra ID Client ID: ${{ inputs.client_id }}"
        echo "Entra ID Client Secret: ${{ inputs.client_secret }}"
        echo "Entra ID Service Principal ID: ${{ inputs.serviceprincipalid }}"
        echo "Entra ID Tenant ID: ${{ inputs.tenantid }}"
        Set-Location -Path ${{ github.action_path }}
        $parameters = @{
           BambooAPIKey = ${{ inputs.bamboo_api_key }}
           BambooSubdomain = ${{ inputs.bamboo_subdomain }}
           ClientID = ${{ inputs.client_id }}
           ClientSecret = ${{ inputs.client_secret }}
           ServicePrincipalID = ${{ inputs.serviceprincipalid }}
           TenantID = ${{ inputs.tenantid }}
          }
          .\APIDrivenProvisioningEntraID.ps1 @parameters


        
      shell: powershell