name: 'API Provisioning'
on:
    workflow_dispatch:
    push:
        branches:
            - main
    #schedule:
    #    - cron: '0 */15 1-23 * *'
    #    - cron: '15/5 1-23 * * *'

jobs:
    API_Provisioning:
        runs-on: windows-latest
        steps:
            - uses: DitaOneSec/EntraID-BulkAPI-Provisioning@main
              with:
                bamboo_api_key:
                    ${{ secrets.API_KEY }}
                bamboo_subdomain:
                    ${{ secrets.SUBDOMAIN }}
                client_id:
                    ${{ secrets.CLIENT_ID }}
                client_secret:
                    ${{ secrets.CLIENT_SECRET }}
                serviceprincipalid:
                    ${{ secrets.SERVICEPRINCIPALID }}
                tenantid:
                    ${{ secrets.TENANT_ID }} 