name: 'API Provisioning'
on:
    workflow_dispatch:

jobs:
    API_Provisioning:
        runs-on: windows-latest
        steps:
            - uses: SuryenduB/EntraID-BulkAPI-Provisioning@main
              with:
                bamboo_api_key:
                    ${{ secrets.BAMBOO_API_KEY }}
                bamboo_subdomain:
                    ${{ secrets.BAMBOO_SUBDOMAIN }}
                client_id:
                    ${{ secrets.CLIENT_ID }}
                client_secret:
                    ${{ secrets.CLIENT_SECRET }}
                serviceprincipalid:
                    ${{ secrets.SERVICEPRINCIPALID }}
                tenantid:
                    ${{ secrets.TENANT_ID }} 